// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebambfitekpeiysqyaix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImViYW1iZml0ZWtwZWl5c3F5YWl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNTIxOTMsImV4cCI6MjA3MDgyODE5M30.iv5tIPxFxx94a5_MvcyxTr0TVaunjet_wQXmnhZExsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});